### ISSUE TITLE
incorrect data

### ISSUE THREAD

**Issue by lostgirljourney** [soumwadeep/Contributed-Repo-Finder#1]
line: https://github.com/soumwadeep/Contributed-Repo-Finder/blob/7caa4314ad6a88496db138d4574189f7b58651e9/src/App.jsx#L109C4-L110C4

![image](https://github.com/soumwadeep/Contributed-Repo-Finder/assets/56036475/15e25338-a514-4b21-83cb-444843f0b1b4)

footer has a spelling mistake
![image](https://github.com/soumwadeep/Contributed-Repo-Finder/assets/56036475/dc7169b1-5a45-4d7a-95b4-2127bcae4072)

**Comment by soumwadeep** [comment]
I Guess Its An API Issue @lostgirljourney 
In My Case Now Its Showing Correct Data

**Comment by soumwadeep** [comment]
By The Way Thank You Very Much For Finding Errors.
